version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shop_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app_user:
    build: ./app_user
    container_name: user_service
    restart: always
    env_file: .env
    ports:
      - "7000:7000"
    depends_on:
      - db

  app_manager:
    build: ./app_manager
    container_name: manager_service
    restart: always
    env_file: .env
    ports:
      - "7001:7001"
    depends_on:
      - db

volumes:
  pgdata:
